apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vault-crd.service-account-name" . }}
  namespace: {{ .Release.Namespace }}

{{- if .Values.vaultCRD.rbac }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-crd-clusterrole
rules:
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - get
  - apiGroups:
      - "koudingspawn.de"
    resources:
      - vault
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
      - events
    verbs:
      - get
      - create
      - patch
      - update
      - delete
      - watch
      - list
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
    verbs:
      - update
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-crd-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-crd-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ include "vault-crd.service-account-name" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}
